apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
  labels:
    app: aws-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      serviceAccountName: asdda-deployment-sa
      containers:
      - name: aws-cli
        image: amazon/aws-cli
        command: ["sleep", "infinity"] # Keeps the container running
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: assda-deployment-db-access
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: assda-deployment-db-access
              key: password